name: GitHub Actions Demo
on: [push]
jobs:
  create-text-txt-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - run: python auto-generate.py
      - run: cat test.md
      - name: test 1
        run: .\.ci\test.sh
